[package]
name = "buildomat"
version = "0.0.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
anyhow = "1"
buildomat-openapi = { path = "../openapi" }
buildomat-common = { path = "../common" }
chrono = "0.4"
dirs-next = "2.0.0"
hiercmd = { git = "https://github.com/jclulow/hiercmd" }
rusty_ulid = "1"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
toml = "0.5.8"
bytes = "1"
futures = "0.3.21"
