[package]
name = "buildomat"
version = "0.0.0"
edition = "2018"
license = "MPL-2.0"

[dependencies]
anyhow = "1"
buildomat-openapi = { path = "../openapi" }
chrono = "0.4"
dirs-next = "2.0.0"
hiercmd = { git = "https://github.com/jclulow/hiercmd" }
rand = "0.8"
reqwest = { version = "^0.11", default-features = false, features = ["json", "native-tls-vendored"]}
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
toml = "0.5.8"
