[package]
name = "wollongong-server"
version = "0.0.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
anyhow = "1.0.41"
base64 = "0.13"
buildomat-openapi = { path = "../../openapi" }
buildomat-common = { path = "../../common" }
chrono = { version = "0.4.19", features = ["serde"] }
dropshot = { git = "https://github.com/oxidecomputer/dropshot" }
hmac-sha256 = "1"
hyper = "0.14"
jsonwebtoken = "7.2.0"
nom_pem = "4.0.0"
octorust = { git = "https://github.com/oxidecomputer/third-party-api-clients", branch = "jclulow" }
reqwest = "0.11.4"
rusty_ulid = "1"
schemars = "0.8.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
slog = "2.7"
thiserror = "1"
tokio = { version = "1.8.1", features = ["full"] }
toml = "0.5.8"
wollongong-common = { path = "../common" }
wollongong-database = { path = "../database" }
