[package]
name = "buildomat-factory-aws"
version = "0.0.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
anyhow = "1"
rusoto_core = "0.48.0"
rusoto_credential = "0.48.0"
rusoto_ec2 = "0.48.0"
rusty_ulid = "1"
slog = "2.7"
slog-term = "2.7"
base64 = "0.13"
tokio = { version = "1", features = [ "full" ] }
serde = { version = "1", features = [ "derive" ] }
toml = "0.5"
buildomat-openapi = { path = "../../openapi" }
buildomat-common = { path = "../../common" }
getopts = "0.2"
