[package]
name = "wollongong-dbtool"
version = "0.0.0"
edition = "2018"
license = "MPL-2.0"

[dependencies]
anyhow = "1"
chrono = { version = "0.4.19", features = ["serde"] }
hiercmd = { git = "https://github.com/jclulow/hiercmd" }
serde_json = "1"
tokio = { version = "1.8.1", features = ["full"] }
wollongong-common = { path = "../common" }
wollongong-database = { path = "../database" }
