[package]
name = "buildomat-github-dbtool"
version = "0.0.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
buildomat-github-database = { path = "../database" }
buildomat-github-hooktypes = { path = "../hooktypes" }

anyhow = { workspace = true }
chrono = { workspace = true }
hiercmd = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
