[package]
name = "buildomat-openapi"
version = "0.0.0"
edition = "2018"

[dependencies]
anyhow = "1.0.44"
chrono = { version = "0.4.19", features = ["serde"] }
percent-encoding = "2.1.0"
reqwest = { version = "0.11.5", features = ["json", "stream"] }
serde = { version = "1.0.130", features = ["derive"] }