[package]
name = "buildomat-bunyan"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.41"
bytes = "1"
chrono = { version = "0.4.19", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_repr = "0.1.8"
serde_with = "1.10.0"
