[package]
name = "callaghan-server"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
anyhow = "1"
buildomat-common = { path = "../../common" }
callaghan-gerrit-client = { path = "../client" }
dropshot = { git = "https://github.com/oxidecomputer/dropshot" }
hyper = "0.14"
schemars = "0.8.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
slog = "2.7"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
toml = "0.5"
futures = "0.3"
html-escape = "0.2.11"
getopts = "0.2"
