[package]
name = "buildomat-github-database"
version = "0.0.0"
edition = "2021"
license = "MPL-2.0"

[lib]
doctest = false

[dependencies]
buildomat-common = { path = "../../common" }
buildomat-database = { path = "../../database" }
buildomat-github-common = { path = "../common" }

anyhow = { workspace = true }
chrono = { workspace = true }
rand = { workspace = true }
rusty_ulid = { workspace = true }
sea-query = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
slog = { workspace = true }
strum = { workspace = true }
