[package]
name = "wollongong-database"
version = "0.0.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
anyhow = { workspace = true }
buildomat-common = { path = "../../common" }
wollongong-common = { path = "../common" }
chrono = { workspace = true }
diesel = { workspace = true }
rand = { workspace = true }
rusty_ulid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
slog = { workspace = true }
thiserror = { workspace = true }
